name: magictrick
description: Rules engine for the Magic Trick card game
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  js: ^0.6.5
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  build_runner: ^2.2.1
  constraint_solver: ^1.0.0
  dartmcts:
    path: ../dartmcts
    # git:
    #   url: https://github.com/dbravender/dartmcts
    #   ref: 98097d9464e6988b3deb3b241bb83ad356b4bd42

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
