name: magictrick
description: Rules engine for the Magic Trick card game
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  build_runner: ^2.2.1
  constraint_solver: ^1.0.0
  dartmcts:
    git:
      url: https://github.com/dbravender/dartmcts
      ref: adec69ca5dd9db3eeccac4c3dbadcf3143cf647e

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
